#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareClassDesign.DatabaseAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PurchaseWeb_v1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PurchaseWeb_v1ConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteCollect")]
		public int deleteCollect([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodity_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id, commodity_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteComment")]
		public int deleteComment([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteMessageByID")]
		public int deleteMessageByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteUserAttention")]
		public int deleteUserAttention([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id_pay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id_gain)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_pay, id_gain);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllComplaint")]
		public ISingleResult<getAllComplaintResult> getAllComplaint()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllComplaintResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllPayUser")]
		public ISingleResult<getAllPayUserResult> getAllPayUser()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllPayUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllPrivateMessageByUser")]
		public ISingleResult<getAllPrivateMessageByUserResult> getAllPrivateMessageByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getAllPrivateMessageByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllPublicMessageByUser")]
		public ISingleResult<getAllPublicMessageByUserResult> getAllPublicMessageByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getAllPublicMessageByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAttentionByUser")]
		public ISingleResult<getAttentionByUserResult> getAttentionByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id_pay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_pay);
			return ((ISingleResult<getAttentionByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNumCommentByUser")]
		public int getNumCommentByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNumPrivateMessageByUser")]
		public int getNumPrivateMessageByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNumPublicMessageByUserName")]
		public int getNumPublicMessageByUserName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getOrderByUserfrom")]
		public ISingleResult<getOrderByUserfromResult> getOrderByUserfrom([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getOrderByUserfromResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getOrderByUserto")]
		public ISingleResult<getOrderByUsertoResult> getOrderByUserto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getOrderByUsertoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getUnreadPrivateMessageByUser")]
		public ISingleResult<getUnreadPrivateMessageByUserResult> getUnreadPrivateMessageByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getUnreadPrivateMessageByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getUnreadPublicMessageByUser")]
		public ISingleResult<getUnreadPublicMessageByUserResult> getUnreadPublicMessageByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getUnreadPublicMessageByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getUserByUserName")]
		public ISingleResult<getUserByUserNameResult> getUserByUserName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getUserByUserNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertAttention")]
		public int insertAttention([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id_pay, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id_gain)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id_pay, user_id_gain);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertCollect")]
		public int insertCollect([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodity_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id, commodity_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertMessage")]
		public int insertMessage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string content, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userfrom, userto, content, type);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertOrder")]
		public int insertOrder([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userfrom, userto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertOrderCommodity")]
		public int insertOrderCommodity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> order_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodity_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), order_id, commodity_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertUser")]
		public int insertUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nickname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string zonestyleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string portraitPath, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string school, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, pwd, nickname, email, phone, zonestyleid, portraitPath, city, school, address);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isRegisted")]
		public ISingleResult<isRegistedResult> isRegisted([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="return", DbType="Bit")] ref System.Nullable<bool> @return)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, pwd, @return);
			@return = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			return ((ISingleResult<isRegistedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateMessageStateByID")]
		public int updateMessageStateByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateOrderStateByID")]
		public int updateOrderStateByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatePopularityCommodity")]
		public int updatePopularityCommodity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatePopularityTag")]
		public int updatePopularityTag([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateRegistedUser")]
		public int updateRegistedUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nickname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string zonestyleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string portraitPath, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string school, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> payamount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> payendtime)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, pwd, nickname, email, phone, zonestyleid, portraitPath, city, school, address, type, payamount, payendtime);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertCommodity")]
		public int insertCommodity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string discription, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> starttimme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> endtime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string picturepath, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kind, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> popularity)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userfrom, name, discription, starttimme, endtime, price, picturepath, kind, popularity);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCommodityByID")]
		public ISingleResult<getCommodityByIDResult> getCommodityByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodity_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), commodity_id);
			return ((ISingleResult<getCommodityByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCommodityByOreder")]
		public ISingleResult<getCommodityByOrederResult> getCommodityByOreder([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> order_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), order_id);
			return ((ISingleResult<getCommodityByOrederResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCommodityByUser")]
		public ISingleResult<getCommodityByUserResult> getCommodityByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getCommodityByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCommentByUser")]
		public ISingleResult<getCommentByUserResult> getCommentByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getCommentByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertComment")]
		public int insertComment([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string content, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodityid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userfrom, userto, content, commodityid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertComplaint")]
		public int insertComplaint([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string content, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodityid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userfrom, userto, content, commodityid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateCommentStateByID")]
		public int updateCommentStateByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateComplaintStateByID")]
		public int updateComplaintStateByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCollectByUser")]
		public ISingleResult<getCollectByUserResult> getCollectByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id);
			return ((ISingleResult<getCollectByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.searchRegistedUser")]
		public ISingleResult<searchRegistedUserResult> searchRegistedUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string keyword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword);
			return ((ISingleResult<searchRegistedUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getStylePathByUser")]
		public int getStylePathByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="return", DbType="NVarChar(500)")] ref string @return)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id, @return);
			@return = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPortraitPathByUser")]
		public int getPortraitPathByUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="return", DbType="NVarChar(500)")] ref string @return)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, @return);
			@return = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllTag")]
		public ISingleResult<getAllTagResult> getAllTag()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllTagResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllDemandCommodity")]
		public ISingleResult<getAllDemandCommodityResult> getAllDemandCommodity()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllDemandCommodityResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertDemandCommodity")]
		public int insertDemandCommodity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string discription, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> starttime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> endtime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kind)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userfrom, name, discription, starttime, endtime, price, kind);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.searchDemandInfo")]
		public ISingleResult<searchDemandInfoResult> searchDemandInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string keyword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kind)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword, kind);
			return ((ISingleResult<searchDemandInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.searchNoPaymentCommodity")]
		public ISingleResult<searchNoPaymentCommodityResult> searchNoPaymentCommodity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string keyword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kind)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword, kind);
			return ((ISingleResult<searchNoPaymentCommodityResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.searchPaymentCommodity")]
		public ISingleResult<searchPaymentCommodityResult> searchPaymentCommodity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string keyword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kind)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword, kind);
			return ((ISingleResult<searchPaymentCommodityResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTagByCommodity")]
		public ISingleResult<getTagByCommodityResult> getTagByCommodity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodity_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), commodity_id);
			return ((ISingleResult<getTagByCommodityResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertTag")]
		public int insertTag([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tag_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodity_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tag_id, commodity_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertTag")]
		public int insertTag1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tag_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> commodity_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tag_id, commodity_id);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class getAllComplaintResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private string _content;
		
		private System.Nullable<int> _state;
		
		private System.Nullable<System.Guid> _commodityid;
		
		public getAllComplaintResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commodityid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> commodityid
		{
			get
			{
				return this._commodityid;
			}
			set
			{
				if ((this._commodityid != value))
				{
					this._commodityid = value;
				}
			}
		}
	}
	
	public partial class getAllPayUserResult
	{
		
		private string _id;
		
		private string _pwd;
		
		private string _nickname;
		
		private string _email;
		
		private string _phone;
		
		private string _zonestyleid;
		
		private string _portraitPath;
		
		private string _city;
		
		private string _school;
		
		private string _address;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<double> _payamount;
		
		private System.Nullable<System.DateTime> _payendtime;
		
		public getAllPayUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this._pwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this._nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zonestyleid", DbType="NVarChar(50)")]
		public string zonestyleid
		{
			get
			{
				return this._zonestyleid;
			}
			set
			{
				if ((this._zonestyleid != value))
				{
					this._zonestyleid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portraitPath", DbType="NVarChar(500)")]
		public string portraitPath
		{
			get
			{
				return this._portraitPath;
			}
			set
			{
				if ((this._portraitPath != value))
				{
					this._portraitPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school", DbType="NVarChar(50)")]
		public string school
		{
			get
			{
				return this._school;
			}
			set
			{
				if ((this._school != value))
				{
					this._school = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payamount", DbType="Float")]
		public System.Nullable<double> payamount
		{
			get
			{
				return this._payamount;
			}
			set
			{
				if ((this._payamount != value))
				{
					this._payamount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payendtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> payendtime
		{
			get
			{
				return this._payendtime;
			}
			set
			{
				if ((this._payendtime != value))
				{
					this._payendtime = value;
				}
			}
		}
	}
	
	public partial class getAllPrivateMessageByUserResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private string _content;
		
		private System.Nullable<int> _state;
		
		private System.Nullable<int> _type;
		
		public getAllPrivateMessageByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
	}
	
	public partial class getAllPublicMessageByUserResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private string _content;
		
		private System.Nullable<int> _state;
		
		private System.Nullable<int> _type;
		
		public getAllPublicMessageByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
	}
	
	public partial class getAttentionByUserResult
	{
		
		private string _id;
		
		private string _pwd;
		
		private string _nickname;
		
		private string _email;
		
		private string _phone;
		
		private string _zonestyleid;
		
		private string _portraitPath;
		
		private string _city;
		
		private string _school;
		
		private string _address;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<double> _payamount;
		
		private System.Nullable<System.DateTime> _payendtime;
		
		public getAttentionByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this._pwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this._nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zonestyleid", DbType="NVarChar(50)")]
		public string zonestyleid
		{
			get
			{
				return this._zonestyleid;
			}
			set
			{
				if ((this._zonestyleid != value))
				{
					this._zonestyleid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portraitPath", DbType="NVarChar(500)")]
		public string portraitPath
		{
			get
			{
				return this._portraitPath;
			}
			set
			{
				if ((this._portraitPath != value))
				{
					this._portraitPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school", DbType="NVarChar(50)")]
		public string school
		{
			get
			{
				return this._school;
			}
			set
			{
				if ((this._school != value))
				{
					this._school = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payamount", DbType="Float")]
		public System.Nullable<double> payamount
		{
			get
			{
				return this._payamount;
			}
			set
			{
				if ((this._payamount != value))
				{
					this._payamount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payendtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> payendtime
		{
			get
			{
				return this._payendtime;
			}
			set
			{
				if ((this._payendtime != value))
				{
					this._payendtime = value;
				}
			}
		}
	}
	
	public partial class getOrderByUserfromResult
	{
		
		private int _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private System.Nullable<int> _state;
		
		public getOrderByUserfromResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
	}
	
	public partial class getOrderByUsertoResult
	{
		
		private int _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private System.Nullable<int> _state;
		
		public getOrderByUsertoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
	}
	
	public partial class getUnreadPrivateMessageByUserResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private string _content;
		
		private System.Nullable<int> _state;
		
		private System.Nullable<int> _type;
		
		public getUnreadPrivateMessageByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
	}
	
	public partial class getUnreadPublicMessageByUserResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private string _content;
		
		private System.Nullable<int> _state;
		
		private System.Nullable<int> _type;
		
		public getUnreadPublicMessageByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
	}
	
	public partial class getUserByUserNameResult
	{
		
		private string _id;
		
		private string _pwd;
		
		private string _nickname;
		
		private string _email;
		
		private string _phone;
		
		private string _zonestyleid;
		
		private string _portraitPath;
		
		private string _city;
		
		private string _school;
		
		private string _address;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<double> _payamount;
		
		private System.Nullable<System.DateTime> _payendtime;
		
		public getUserByUserNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this._pwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this._nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zonestyleid", DbType="NVarChar(50)")]
		public string zonestyleid
		{
			get
			{
				return this._zonestyleid;
			}
			set
			{
				if ((this._zonestyleid != value))
				{
					this._zonestyleid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portraitPath", DbType="NVarChar(500)")]
		public string portraitPath
		{
			get
			{
				return this._portraitPath;
			}
			set
			{
				if ((this._portraitPath != value))
				{
					this._portraitPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school", DbType="NVarChar(50)")]
		public string school
		{
			get
			{
				return this._school;
			}
			set
			{
				if ((this._school != value))
				{
					this._school = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payamount", DbType="Float")]
		public System.Nullable<double> payamount
		{
			get
			{
				return this._payamount;
			}
			set
			{
				if ((this._payamount != value))
				{
					this._payamount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payendtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> payendtime
		{
			get
			{
				return this._payendtime;
			}
			set
			{
				if ((this._payendtime != value))
				{
					this._payendtime = value;
				}
			}
		}
	}
	
	public partial class isRegistedResult
	{
		
		private string _id;
		
		private string _pwd;
		
		private string _nickname;
		
		private string _email;
		
		private string _phone;
		
		private string _zonestyleid;
		
		private string _portraitPath;
		
		private string _city;
		
		private string _school;
		
		private string _address;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<double> _payamount;
		
		private System.Nullable<System.DateTime> _payendtime;
		
		public isRegistedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this._pwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this._nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zonestyleid", DbType="NVarChar(50)")]
		public string zonestyleid
		{
			get
			{
				return this._zonestyleid;
			}
			set
			{
				if ((this._zonestyleid != value))
				{
					this._zonestyleid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portraitPath", DbType="NVarChar(500)")]
		public string portraitPath
		{
			get
			{
				return this._portraitPath;
			}
			set
			{
				if ((this._portraitPath != value))
				{
					this._portraitPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school", DbType="NVarChar(50)")]
		public string school
		{
			get
			{
				return this._school;
			}
			set
			{
				if ((this._school != value))
				{
					this._school = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payamount", DbType="Float")]
		public System.Nullable<double> payamount
		{
			get
			{
				return this._payamount;
			}
			set
			{
				if ((this._payamount != value))
				{
					this._payamount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payendtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> payendtime
		{
			get
			{
				return this._payendtime;
			}
			set
			{
				if ((this._payendtime != value))
				{
					this._payendtime = value;
				}
			}
		}
	}
	
	public partial class getCommodityByIDResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private string _picturepath;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public getCommodityByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picturepath", DbType="NVarChar(500)")]
		public string picturepath
		{
			get
			{
				return this._picturepath;
			}
			set
			{
				if ((this._picturepath != value))
				{
					this._picturepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class getCommodityByOrederResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private string _picturepath;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public getCommodityByOrederResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picturepath", DbType="NVarChar(500)")]
		public string picturepath
		{
			get
			{
				return this._picturepath;
			}
			set
			{
				if ((this._picturepath != value))
				{
					this._picturepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class getCommodityByUserResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private string _picturepath;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public getCommodityByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picturepath", DbType="NVarChar(500)")]
		public string picturepath
		{
			get
			{
				return this._picturepath;
			}
			set
			{
				if ((this._picturepath != value))
				{
					this._picturepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class getCommentByUserResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _userto;
		
		private string _content;
		
		private System.Nullable<int> _state;
		
		private System.Nullable<System.Guid> _commodityid;
		
		public getCommentByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userto", DbType="NVarChar(50)")]
		public string userto
		{
			get
			{
				return this._userto;
			}
			set
			{
				if ((this._userto != value))
				{
					this._userto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commodityid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> commodityid
		{
			get
			{
				return this._commodityid;
			}
			set
			{
				if ((this._commodityid != value))
				{
					this._commodityid = value;
				}
			}
		}
	}
	
	public partial class getCollectByUserResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private string _picturepath;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public getCollectByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picturepath", DbType="NVarChar(500)")]
		public string picturepath
		{
			get
			{
				return this._picturepath;
			}
			set
			{
				if ((this._picturepath != value))
				{
					this._picturepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class searchRegistedUserResult
	{
		
		private string _id;
		
		private string _pwd;
		
		private string _nickname;
		
		private string _email;
		
		private string _phone;
		
		private string _zonestyleid;
		
		private string _portraitPath;
		
		private string _city;
		
		private string _school;
		
		private string _address;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<double> _payamount;
		
		private System.Nullable<System.DateTime> _payendtime;
		
		public searchRegistedUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this._pwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this._nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zonestyleid", DbType="NVarChar(50)")]
		public string zonestyleid
		{
			get
			{
				return this._zonestyleid;
			}
			set
			{
				if ((this._zonestyleid != value))
				{
					this._zonestyleid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portraitPath", DbType="NVarChar(500)")]
		public string portraitPath
		{
			get
			{
				return this._portraitPath;
			}
			set
			{
				if ((this._portraitPath != value))
				{
					this._portraitPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school", DbType="NVarChar(50)")]
		public string school
		{
			get
			{
				return this._school;
			}
			set
			{
				if ((this._school != value))
				{
					this._school = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payamount", DbType="Float")]
		public System.Nullable<double> payamount
		{
			get
			{
				return this._payamount;
			}
			set
			{
				if ((this._payamount != value))
				{
					this._payamount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payendtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> payendtime
		{
			get
			{
				return this._payendtime;
			}
			set
			{
				if ((this._payendtime != value))
				{
					this._payendtime = value;
				}
			}
		}
	}
	
	public partial class getAllTagResult
	{
		
		private string _id;
		
		private System.Nullable<int> _popularity;
		
		public getAllTagResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class getAllDemandCommodityResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public getAllDemandCommodityResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class searchDemandInfoResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public searchDemandInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class searchNoPaymentCommodityResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private string _picturepath;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public searchNoPaymentCommodityResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picturepath", DbType="NVarChar(500)")]
		public string picturepath
		{
			get
			{
				return this._picturepath;
			}
			set
			{
				if ((this._picturepath != value))
				{
					this._picturepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class searchPaymentCommodityResult
	{
		
		private System.Guid _id;
		
		private string _userfrom;
		
		private string _name;
		
		private string _discription;
		
		private System.Nullable<System.DateTime> _starttime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private System.Nullable<double> _price;
		
		private string _picturepath;
		
		private System.Nullable<int> _kind;
		
		private System.Nullable<int> _popularity;
		
		public searchPaymentCommodityResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userfrom", DbType="NVarChar(50)")]
		public string userfrom
		{
			get
			{
				return this._userfrom;
			}
			set
			{
				if ((this._userfrom != value))
				{
					this._userfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(500)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this._discription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this._starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this._endtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picturepath", DbType="NVarChar(500)")]
		public string picturepath
		{
			get
			{
				return this._picturepath;
			}
			set
			{
				if ((this._picturepath != value))
				{
					this._picturepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="Int")]
		public System.Nullable<int> kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
	
	public partial class getTagByCommodityResult
	{
		
		private string _id;
		
		private System.Nullable<int> _popularity;
		
		public getTagByCommodityResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popularity", DbType="Int")]
		public System.Nullable<int> popularity
		{
			get
			{
				return this._popularity;
			}
			set
			{
				if ((this._popularity != value))
				{
					this._popularity = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
